### PR TITLE
Implemented Star Rating to the Reviews and Actvities

### PR DESCRIPTION
**Pull request by StefanTrueitt**
Implemented Star Rating to the Reviews and Actvities

### CODE REVIEW

**Comment by Justin8912** [comment]
Hey @StefanTrueitt , I tried to pull this request and run it but I was getting this error when clicking the 'Make API Call' button. I'm not sure if this is becasue I dont have an API key in the .env.local or if its something else, just wanted to see if you were seeing this on your side too. 
Screen Shot 2023-03-24 at 10 20 19 PM

**Comment by StefanTrueitt** [comment]
Oh yeah @Justin8912 . So that's the CORS thing that we have to do before presentation. After we hit the API button, we have to go to the networks tab, double click the red text, then requesting temporary access.

**Comment by Justin8912** [comment]
@StefanTrueitt Ahh! Okay, with that this looks great! I'll go aead and merge this now.

**Comment by StefanTrueitt** [comment]
Thank you @Justin8912 !

**Pull request merged**
