### PR TITLE
Login

### PR DESCRIPTION
**Pull request by Justin8912**
Added functionality for cookies when a user registers and logs in. 
The main files that were changed were:
1. All the files in ./src/pages/Login/

Please try to pull down and create a user and log into it. To check if the cookie was set properly, open up the console, navigate to the application section, click on cookies from localhost:3000 and make sure one was set that is called userId. 

Currently I have all cookies ready to expire within a day of login. I have not implemented a log out button yet since I wanted to get this out there in case any of y'all needed it!

### CODE REVIEW

**Comment by bossertjack** [comment]
Cookie popped up, but server responded with a 400 error
Nit : Registration modal should close after creating account.

**Comment by Justin8912** [comment]
@bossertjack When were you getting a 400 error? I tried creating an account, logging into one, and logging out and wasnt able to get it. 

I will fix the registration button, thanks for the heads up!

**Comment by Justin8912** [comment]
@bossertjack Everything should be working now. I think the only issue I am currently facing is testing the authentication through facebook because it will only allow requests from an https security protocol but I can only connect to my localhost with http. I want to see how it will run on the server and see if there is anything that should be changed at that point. 

Try to pull down and make sure those errors aren't coming up anymore!

**Comment by andrengo94** [comment]
@Justin8912 Thank you for your work on this! Cookie shows up for me and goes away upon clicking logout 
I am not seeing any errors when creating a user, or logging in using Google

**Pull request merged**
